package entity;
// Generated Sep 5, 2012 10:40:14 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Areas generated by hbm2java
 */
public class Areas  implements java.io.Serializable {


     private int areaId;
     private Serializable areaName;
     private Serializable descriptions;
     private Set<HotelRestaurant> hotelRestaurants = new HashSet<HotelRestaurant>(0);

    public Areas() {
    }

	
    public Areas(int areaId) {
        this.areaId = areaId;
    }
    public Areas(int areaId, Serializable areaName, Serializable descriptions, Set<HotelRestaurant> hotelRestaurants) {
       this.areaId = areaId;
       this.areaName = areaName;
       this.descriptions = descriptions;
       this.hotelRestaurants = hotelRestaurants;
    }
   
    public int getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(int areaId) {
        this.areaId = areaId;
    }
    public Serializable getAreaName() {
        return this.areaName;
    }
    
    public void setAreaName(Serializable areaName) {
        this.areaName = areaName;
    }
    public Serializable getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(Serializable descriptions) {
        this.descriptions = descriptions;
    }
    public Set<HotelRestaurant> getHotelRestaurants() {
        return this.hotelRestaurants;
    }
    
    public void setHotelRestaurants(Set<HotelRestaurant> hotelRestaurants) {
        this.hotelRestaurants = hotelRestaurants;
    }




}


