package entity;
// Generated Sep 20, 2012 1:15:31 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * Bookingparty generated by hbm2java
 */
public class Bookingparty  implements java.io.Serializable {


     private int id;
     private Serializable fullName;
     private Serializable email;
     private Serializable phone;
     private Serializable address;
     private Integer scale;
     private Date time;
     private Serializable conntent;

    public Bookingparty() {
    }

	
    public Bookingparty(int id) {
        this.id = id;
    }
    public Bookingparty(int id, Serializable fullName, Serializable email, Serializable phone, Serializable address, Integer scale, Date time, Serializable conntent) {
       this.id = id;
       this.fullName = fullName;
       this.email = email;
       this.phone = phone;
       this.address = address;
       this.scale = scale;
       this.time = time;
       this.conntent = conntent;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getFullName() {
        return this.fullName;
    }
    
    public void setFullName(Serializable fullName) {
        this.fullName = fullName;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Serializable getPhone() {
        return this.phone;
    }
    
    public void setPhone(Serializable phone) {
        this.phone = phone;
    }
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }
    public Integer getScale() {
        return this.scale;
    }
    
    public void setScale(Integer scale) {
        this.scale = scale;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Serializable getConntent() {
        return this.conntent;
    }
    
    public void setConntent(Serializable conntent) {
        this.conntent = conntent;
    }




}


