package entity;
// Generated Sep 5, 2012 10:40:14 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Booking generated by hbm2java
 */
public class Booking  implements java.io.Serializable {


     private int bookingId;
     private Users users;
     private HotelRestaurant hotelRestaurant;
     private Date timeStart;
     private Date timeEnd;
     private Boolean bookingStatus;
     private Serializable notes;
     private String tokenNumber;
     private Set<Roombooking> roombookings = new HashSet<Roombooking>(0);
     private Set<Tablebooking> tablebookings = new HashSet<Tablebooking>(0);

    public Booking() {
    }

	
    public Booking(int bookingId) {
        this.bookingId = bookingId;
    }
    public Booking(int bookingId, Users users, HotelRestaurant hotelRestaurant, Date timeStart, Date timeEnd, Boolean bookingStatus, Serializable notes, String tokenNumber, Set<Roombooking> roombookings, Set<Tablebooking> tablebookings) {
       this.bookingId = bookingId;
       this.users = users;
       this.hotelRestaurant = hotelRestaurant;
       this.timeStart = timeStart;
       this.timeEnd = timeEnd;
       this.bookingStatus = bookingStatus;
       this.notes = notes;
       this.tokenNumber = tokenNumber;
       this.roombookings = roombookings;
       this.tablebookings = tablebookings;
    }
   
    public int getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(int bookingId) {
        this.bookingId = bookingId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public HotelRestaurant getHotelRestaurant() {
        return this.hotelRestaurant;
    }
    
    public void setHotelRestaurant(HotelRestaurant hotelRestaurant) {
        this.hotelRestaurant = hotelRestaurant;
    }
    public Date getTimeStart() {
        return this.timeStart;
    }
    
    public void setTimeStart(Date timeStart) {
        this.timeStart = timeStart;
    }
    public Date getTimeEnd() {
        return this.timeEnd;
    }
    
    public void setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }
    public Boolean getBookingStatus() {
        return this.bookingStatus;
    }
    
    public void setBookingStatus(Boolean bookingStatus) {
        this.bookingStatus = bookingStatus;
    }
    public Serializable getNotes() {
        return this.notes;
    }
    
    public void setNotes(Serializable notes) {
        this.notes = notes;
    }
    public String getTokenNumber() {
        return this.tokenNumber;
    }
    
    public void setTokenNumber(String tokenNumber) {
        this.tokenNumber = tokenNumber;
    }
    public Set<Roombooking> getRoombookings() {
        return this.roombookings;
    }
    
    public void setRoombookings(Set<Roombooking> roombookings) {
        this.roombookings = roombookings;
    }
    public Set<Tablebooking> getTablebookings() {
        return this.tablebookings;
    }
    
    public void setTablebookings(Set<Tablebooking> tablebookings) {
        this.tablebookings = tablebookings;
    }




}


