package entity;
// Generated Sep 5, 2012 10:40:14 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * Feedback generated by hbm2java
 */
public class Feedback  implements java.io.Serializable {


     private int feedBackId;
     private Serializable fullName;
     private Serializable email;
     private Serializable title;
     private Serializable content;
     private Date dateCreate;

    public Feedback() {
    }

	
    public Feedback(int feedBackId) {
        this.feedBackId = feedBackId;
    }
    public Feedback(int feedBackId, Serializable fullName, Serializable email, Serializable title, Serializable content, Date dateCreate) {
       this.feedBackId = feedBackId;
       this.fullName = fullName;
       this.email = email;
       this.title = title;
       this.content = content;
       this.dateCreate = dateCreate;
    }
   
    public int getFeedBackId() {
        return this.feedBackId;
    }
    
    public void setFeedBackId(int feedBackId) {
        this.feedBackId = feedBackId;
    }
    public Serializable getFullName() {
        return this.fullName;
    }
    
    public void setFullName(Serializable fullName) {
        this.fullName = fullName;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Serializable getTitle() {
        return this.title;
    }
    
    public void setTitle(Serializable title) {
        this.title = title;
    }
    public Serializable getContent() {
        return this.content;
    }
    
    public void setContent(Serializable content) {
        this.content = content;
    }
    public Date getDateCreate() {
        return this.dateCreate;
    }
    
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }




}


