package entity;
// Generated Sep 5, 2012 10:40:14 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Foods generated by hbm2java
 */
public class Foods  implements java.io.Serializable {


     private int foodId;
     private Typefoods typefoods;
     private Serializable foodName;
     private Double foodPrices;
     private Serializable foodDescription;
     private Boolean foodStatus;
     private Set<HomedeliveryDetails> homedeliveryDetailses = new HashSet<HomedeliveryDetails>(0);
     private Set<Images> imageses = new HashSet<Images>(0);

    public Foods() {
    }

	
    public Foods(int foodId) {
        this.foodId = foodId;
    }
    public Foods(int foodId, Typefoods typefoods, Serializable foodName, Double foodPrices, Serializable foodDescription, Boolean foodStatus, Set<HomedeliveryDetails> homedeliveryDetailses, Set<Images> imageses) {
       this.foodId = foodId;
       this.typefoods = typefoods;
       this.foodName = foodName;
       this.foodPrices = foodPrices;
       this.foodDescription = foodDescription;
       this.foodStatus = foodStatus;
       this.homedeliveryDetailses = homedeliveryDetailses;
       this.imageses = imageses;
    }
   
    public int getFoodId() {
        return this.foodId;
    }
    
    public void setFoodId(int foodId) {
        this.foodId = foodId;
    }
    public Typefoods getTypefoods() {
        return this.typefoods;
    }
    
    public void setTypefoods(Typefoods typefoods) {
        this.typefoods = typefoods;
    }
    public Serializable getFoodName() {
        return this.foodName;
    }
    
    public void setFoodName(Serializable foodName) {
        this.foodName = foodName;
    }
    public Double getFoodPrices() {
        return this.foodPrices;
    }
    
    public void setFoodPrices(Double foodPrices) {
        this.foodPrices = foodPrices;
    }
    public Serializable getFoodDescription() {
        return this.foodDescription;
    }
    
    public void setFoodDescription(Serializable foodDescription) {
        this.foodDescription = foodDescription;
    }
    public Boolean getFoodStatus() {
        return this.foodStatus;
    }
    
    public void setFoodStatus(Boolean foodStatus) {
        this.foodStatus = foodStatus;
    }
    public Set<HomedeliveryDetails> getHomedeliveryDetailses() {
        return this.homedeliveryDetailses;
    }
    
    public void setHomedeliveryDetailses(Set<HomedeliveryDetails> homedeliveryDetailses) {
        this.homedeliveryDetailses = homedeliveryDetailses;
    }
    public Set<Images> getImageses() {
        return this.imageses;
    }
    
    public void setImageses(Set<Images> imageses) {
        this.imageses = imageses;
    }




}


