package entity;
// Generated Sep 27, 2012 7:29:24 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Foods generated by hbm2java
 */
public class Foods  implements java.io.Serializable {


     private int foodId;
     private Typefoods typefoods;
     private String foodName;
     private Double foodPrices;
     private String foodDescription;
     private Boolean foodStatus;
     private Set<HomedeliveryDetails> homedeliveryDetailses = new HashSet<HomedeliveryDetails>(0);

    public Foods() {
    }

	
    public Foods(int foodId) {
        this.foodId = foodId;
    }
    public Foods(int foodId, Typefoods typefoods, String foodName, Double foodPrices, String foodDescription, Boolean foodStatus, Set<HomedeliveryDetails> homedeliveryDetailses) {
       this.foodId = foodId;
       this.typefoods = typefoods;
       this.foodName = foodName;
       this.foodPrices = foodPrices;
       this.foodDescription = foodDescription;
       this.foodStatus = foodStatus;
       this.homedeliveryDetailses = homedeliveryDetailses;
    }
   
    public int getFoodId() {
        return this.foodId;
    }
    
    public void setFoodId(int foodId) {
        this.foodId = foodId;
    }
    public Typefoods getTypefoods() {
        return this.typefoods;
    }
    
    public void setTypefoods(Typefoods typefoods) {
        this.typefoods = typefoods;
    }
    public String getFoodName() {
        return this.foodName;
    }
    
    public void setFoodName(String foodName) {
        this.foodName = foodName;
    }
    public Double getFoodPrices() {
        return this.foodPrices;
    }
    
    public void setFoodPrices(Double foodPrices) {
        this.foodPrices = foodPrices;
    }
    public String getFoodDescription() {
        return this.foodDescription;
    }
    
    public void setFoodDescription(String foodDescription) {
        this.foodDescription = foodDescription;
    }
    public Boolean getFoodStatus() {
        return this.foodStatus;
    }
    
    public void setFoodStatus(Boolean foodStatus) {
        this.foodStatus = foodStatus;
    }
    public Set<HomedeliveryDetails> getHomedeliveryDetailses() {
        return this.homedeliveryDetailses;
    }
    
    public void setHomedeliveryDetailses(Set<HomedeliveryDetails> homedeliveryDetailses) {
        this.homedeliveryDetailses = homedeliveryDetailses;
    }




}


