package entity;
// Generated Sep 5, 2012 10:40:14 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * HotelRestaurant generated by hbm2java
 */
public class HotelRestaurant  implements java.io.Serializable {


     private int hrid;
     private String hrname;
     private String hraddress;
     private String hrphone;
     private String hremail;
     private String hrinfo;
     private Boolean hrstatus;
     private Set<Booking> bookings = new HashSet<Booking>(0);

    public HotelRestaurant() {
    }

	
    public HotelRestaurant(int hrid) {
        this.hrid = hrid;
    }
    public HotelRestaurant(int hrid, String hrname, String hraddress, String hrphone, String hremail, String hrinfo, Boolean hrstatus, Set<Booking> bookings) {
       this.hrid = hrid;
       this.hrname = hrname;
       this.hraddress = hraddress;
       this.hrphone = hrphone;
       this.hremail = hremail;
       this.hrinfo = hrinfo;
       this.hrstatus = hrstatus;
       this.bookings = bookings;
    }
   
    public int getHrid() {
        return this.hrid;
    }
    
    public void setHrid(int hrid) {
        this.hrid = hrid;
    }
    public Serializable getHrname() {
        return this.hrname;
    }
    
    public void setHrname(String hrname) {
        this.hrname = hrname;
    }
    public Serializable getHraddress() {
        return this.hraddress;
    }
    
    public void setHraddress(String hraddress) {
        this.hraddress = hraddress;
    }
    public Serializable getHrphone() {
        return this.hrphone;
    }
    
    public void setHrphone(String hrphone) {
        this.hrphone = hrphone;
    }
    public Serializable getHremail() {
        return this.hremail;
    }
    
    public void setHremail(String hremail) {
        this.hremail = hremail;
    }
    public Serializable getHrinfo() {
        return this.hrinfo;
    }
    
    public void setHrinfo(String hrinfo) {
        this.hrinfo = hrinfo;
    }
    
    public Boolean getHrstatus() {
        return this.hrstatus;
    }
    
    public void setHrstatus(Boolean hrstatus) {
        this.hrstatus = hrstatus;
    }
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }




}


