package entity;
// Generated Sep 5, 2012 10:40:14 PM by Hibernate Tools 3.2.1.GA



/**
 * Images generated by hbm2java
 */
public class Images  implements java.io.Serializable {


     private int imageId;
     private Integer typeImage;
     private Integer id;
     private String descriptions;
     private String imageLink;

    public Images() {
    }

    public Images(int imageId) {
        this.imageId = imageId;
    }
    public Images(int imageId, Integer typeImage, String descriptions, String imageLink) {
       this.imageId = imageId;
       this.typeImage = typeImage;
       this.descriptions = descriptions;
       this.imageLink = imageLink;
    }
   
    public int getImageId() {
        return this.imageId;
    }
    
    public void setImageId(int imageId) {
        this.imageId = imageId;
    }
    
    public Integer getTypeImage() {
        return this.typeImage;
    }
    
    public void setTypeImage(Integer typeImage) {
        this.typeImage = typeImage;
    }
    
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    
    public String getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }
    public String getImageLink() {
        return this.imageLink;
    }
    
    public void setImageLink(String imageLink) {
        this.imageLink = imageLink;
    }




}


