package entity;
// Generated Sep 5, 2012 10:40:14 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Typetable generated by hbm2java
 */
public class Typetable  implements java.io.Serializable {


     private int typeTableId;
     private Serializable typeTableName;
     private Serializable typeTableDescription;
     private Double tablePrice;
     private Set<RestaurantTables> restaurantTableses = new HashSet<RestaurantTables>(0);

    public Typetable() {
    }

	
    public Typetable(int typeTableId) {
        this.typeTableId = typeTableId;
    }
    public Typetable(int typeTableId, Serializable typeTableName, Serializable typeTableDescription, Double tablePrice, Set<RestaurantTables> restaurantTableses) {
       this.typeTableId = typeTableId;
       this.typeTableName = typeTableName;
       this.typeTableDescription = typeTableDescription;
       this.tablePrice = tablePrice;
       this.restaurantTableses = restaurantTableses;
    }
   
    public int getTypeTableId() {
        return this.typeTableId;
    }
    
    public void setTypeTableId(int typeTableId) {
        this.typeTableId = typeTableId;
    }
    public Serializable getTypeTableName() {
        return this.typeTableName;
    }
    
    public void setTypeTableName(Serializable typeTableName) {
        this.typeTableName = typeTableName;
    }
    public Serializable getTypeTableDescription() {
        return this.typeTableDescription;
    }
    
    public void setTypeTableDescription(Serializable typeTableDescription) {
        this.typeTableDescription = typeTableDescription;
    }
    public Double getTablePrice() {
        return this.tablePrice;
    }
    
    public void setTablePrice(Double tablePrice) {
        this.tablePrice = tablePrice;
    }
    public Set<RestaurantTables> getRestaurantTableses() {
        return this.restaurantTableses;
    }
    
    public void setRestaurantTableses(Set<RestaurantTables> restaurantTableses) {
        this.restaurantTableses = restaurantTableses;
    }




}


