package entity;
// Generated Sep 27, 2012 7:29:24 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Homedelivery generated by hbm2java
 */
public class Homedelivery  implements java.io.Serializable {


     private int bookingId;
     private Users users;
     private Date deliveryTime;
     private Double shipMoney;
     private Double total;
     private Set<HomedeliveryDetails> homedeliveryDetailses = new HashSet<HomedeliveryDetails>(0);

    public Homedelivery() {
    }

	
    public Homedelivery(int bookingId) {
        this.bookingId = bookingId;
    }
    public Homedelivery(int bookingId, Users users, Date deliveryTime, Double shipMoney, Double total, Set<HomedeliveryDetails> homedeliveryDetailses) {
       this.bookingId = bookingId;
       this.users = users;
       this.deliveryTime = deliveryTime;
       this.shipMoney = shipMoney;
       this.total = total;
       this.homedeliveryDetailses = homedeliveryDetailses;
    }
   
    public int getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(int bookingId) {
        this.bookingId = bookingId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getDeliveryTime() {
        return this.deliveryTime;
    }
    
    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }
    public Double getShipMoney() {
        return this.shipMoney;
    }
    
    public void setShipMoney(Double shipMoney) {
        this.shipMoney = shipMoney;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Set<HomedeliveryDetails> getHomedeliveryDetailses() {
        return this.homedeliveryDetailses;
    }
    
    public void setHomedeliveryDetailses(Set<HomedeliveryDetails> homedeliveryDetailses) {
        this.homedeliveryDetailses = homedeliveryDetailses;
    }




}


