package entity;
// Generated Sep 5, 2012 10:40:14 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * News generated by hbm2java
 */
public class News  implements java.io.Serializable {


     private int newsId;
     private Users users;
     private Serializable newsTitle;
     private Serializable newsContent;
     private Date timeUpNews;

    public News() {
    }

	
    public News(int newsId) {
        this.newsId = newsId;
    }
    public News(int newsId, Users users, Serializable newsTitle, Serializable newsContent, Date timeUpNews) {
       this.newsId = newsId;
       this.users = users;
       this.newsTitle = newsTitle;
       this.newsContent = newsContent;
       this.timeUpNews = timeUpNews;
    }
   
    public int getNewsId() {
        return this.newsId;
    }
    
    public void setNewsId(int newsId) {
        this.newsId = newsId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Serializable getNewsTitle() {
        return this.newsTitle;
    }
    
    public void setNewsTitle(Serializable newsTitle) {
        this.newsTitle = newsTitle;
    }
    public Serializable getNewsContent() {
        return this.newsContent;
    }
    
    public void setNewsContent(Serializable newsContent) {
        this.newsContent = newsContent;
    }
    public Date getTimeUpNews() {
        return this.timeUpNews;
    }
    
    public void setTimeUpNews(Date timeUpNews) {
        this.timeUpNews = timeUpNews;
    }




}


