package entity;
// Generated Sep 27, 2012 7:29:24 AM by Hibernate Tools 3.2.1.GA



/**
 * Tablebooking generated by hbm2java
 */
public class Tablebooking  implements java.io.Serializable {


     private int bookingDetailsId;
     private RestaurantTables restaurantTables;
     private Booking booking;

    public Tablebooking() {
    }

	
    public Tablebooking(int bookingDetailsId) {
        this.bookingDetailsId = bookingDetailsId;
    }
    public Tablebooking(int bookingDetailsId, RestaurantTables restaurantTables, Booking booking) {
       this.bookingDetailsId = bookingDetailsId;
       this.restaurantTables = restaurantTables;
       this.booking = booking;
    }
   
    public int getBookingDetailsId() {
        return this.bookingDetailsId;
    }
    
    public void setBookingDetailsId(int bookingDetailsId) {
        this.bookingDetailsId = bookingDetailsId;
    }
    public RestaurantTables getRestaurantTables() {
        return this.restaurantTables;
    }
    
    public void setRestaurantTables(RestaurantTables restaurantTables) {
        this.restaurantTables = restaurantTables;
    }
    public Booking getBooking() {
        return this.booking;
    }
    
    public void setBooking(Booking booking) {
        this.booking = booking;
    }




}


