package entity;
// Generated Sep 27, 2012 7:29:24 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int accountId;
     private Roles roles;
     private Serializable userName;
     private Serializable userPassword;
     private Serializable userFirstName;
     private Serializable userLastName;
     private Date userBirthDay;
     private Boolean userGender;
     private Serializable userAddress;
     private Serializable userPhone;
     private Serializable userEmail;
     private Boolean allowLogin;
     private Set<Homedelivery> homedeliveries = new HashSet<Homedelivery>(0);
     private Set<News> newses = new HashSet<News>(0);
     private Set<Booking> bookings = new HashSet<Booking>(0);

    public Users() {
    }

	
    public Users(int accountId, Serializable userName, Serializable userPassword) {
        this.accountId = accountId;
        this.userName = userName;
        this.userPassword = userPassword;
    }
    public Users(int accountId, Roles roles, Serializable userName, Serializable userPassword, Serializable userFirstName, Serializable userLastName, Date userBirthDay, Boolean userGender, Serializable userAddress, Serializable userPhone, Serializable userEmail, Boolean allowLogin, Set<Homedelivery> homedeliveries, Set<News> newses, Set<Booking> bookings) {
       this.accountId = accountId;
       this.roles = roles;
       this.userName = userName;
       this.userPassword = userPassword;
       this.userFirstName = userFirstName;
       this.userLastName = userLastName;
       this.userBirthDay = userBirthDay;
       this.userGender = userGender;
       this.userAddress = userAddress;
       this.userPhone = userPhone;
       this.userEmail = userEmail;
       this.allowLogin = allowLogin;
       this.homedeliveries = homedeliveries;
       this.newses = newses;
       this.bookings = bookings;
    }
   
    public int getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public Serializable getUserName() {
        return this.userName;
    }
    
    public void setUserName(Serializable userName) {
        this.userName = userName;
    }
    public Serializable getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(Serializable userPassword) {
        this.userPassword = userPassword;
    }
    public Serializable getUserFirstName() {
        return this.userFirstName;
    }
    
    public void setUserFirstName(Serializable userFirstName) {
        this.userFirstName = userFirstName;
    }
    public Serializable getUserLastName() {
        return this.userLastName;
    }
    
    public void setUserLastName(Serializable userLastName) {
        this.userLastName = userLastName;
    }
    public Date getUserBirthDay() {
        return this.userBirthDay;
    }
    
    public void setUserBirthDay(Date userBirthDay) {
        this.userBirthDay = userBirthDay;
    }
    public Boolean getUserGender() {
        return this.userGender;
    }
    
    public void setUserGender(Boolean userGender) {
        this.userGender = userGender;
    }
    public Serializable getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(Serializable userAddress) {
        this.userAddress = userAddress;
    }
    public Serializable getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(Serializable userPhone) {
        this.userPhone = userPhone;
    }
    public Serializable getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(Serializable userEmail) {
        this.userEmail = userEmail;
    }
    public Boolean getAllowLogin() {
        return this.allowLogin;
    }
    
    public void setAllowLogin(Boolean allowLogin) {
        this.allowLogin = allowLogin;
    }
    public Set<Homedelivery> getHomedeliveries() {
        return this.homedeliveries;
    }
    
    public void setHomedeliveries(Set<Homedelivery> homedeliveries) {
        this.homedeliveries = homedeliveries;
    }
    public Set<News> getNewses() {
        return this.newses;
    }
    
    public void setNewses(Set<News> newses) {
        this.newses = newses;
    }
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }




}


