package entity;
// Generated Sep 27, 2012 7:29:24 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Typetable generated by hbm2java
 */
public class Typetable  implements java.io.Serializable {


     private int typeTableId;
     private String typeTableName;
     private String typeTableDescription;
     private Double tablePrice;
     private Set<RestaurantTables> restaurantTableses = new HashSet<RestaurantTables>(0);

    public Typetable() {
    }

	
    public Typetable(int typeTableId) {
        this.typeTableId = typeTableId;
    }
    public Typetable(int typeTableId, String typeTableName, String typeTableDescription, Double tablePrice, Set<RestaurantTables> restaurantTableses) {
       this.typeTableId = typeTableId;
       this.typeTableName = typeTableName;
       this.typeTableDescription = typeTableDescription;
       this.tablePrice = tablePrice;
       this.restaurantTableses = restaurantTableses;
    }
   
    public int getTypeTableId() {
        return this.typeTableId;
    }
    
    public void setTypeTableId(int typeTableId) {
        this.typeTableId = typeTableId;
    }
    public String getTypeTableName() {
        return this.typeTableName;
    }
    
    public void setTypeTableName(String typeTableName) {
        this.typeTableName = typeTableName;
    }
    public String getTypeTableDescription() {
        return this.typeTableDescription;
    }
    
    public void setTypeTableDescription(String typeTableDescription) {
        this.typeTableDescription = typeTableDescription;
    }
    public Double getTablePrice() {
        return this.tablePrice;
    }
    
    public void setTablePrice(Double tablePrice) {
        this.tablePrice = tablePrice;
    }
    public Set<RestaurantTables> getRestaurantTableses() {
        return this.restaurantTableses;
    }
    
    public void setRestaurantTableses(Set<RestaurantTables> restaurantTableses) {
        this.restaurantTableses = restaurantTableses;
    }




}


