package entity;
// Generated Sep 27, 2012 7:29:24 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Typeimages generated by hbm2java
 */
public class Typeimages  implements java.io.Serializable {


     private int typeImageId;
     private String typeName;
     private String typeDescription;
     private Set<Images> imageses = new HashSet<Images>(0);

    public Typeimages() {
    }

	
    public Typeimages(int typeImageId) {
        this.typeImageId = typeImageId;
    }
    public Typeimages(int typeImageId, String typeName, String typeDescription, Set<Images> imageses) {
       this.typeImageId = typeImageId;
       this.typeName = typeName;
       this.typeDescription = typeDescription;
       this.imageses = imageses;
    }
   
    public int getTypeImageId() {
        return this.typeImageId;
    }
    
    public void setTypeImageId(int typeImageId) {
        this.typeImageId = typeImageId;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public String getTypeDescription() {
        return this.typeDescription;
    }
    
    public void setTypeDescription(String typeDescription) {
        this.typeDescription = typeDescription;
    }
    public Set<Images> getImageses() {
        return this.imageses;
    }
    
    public void setImageses(Set<Images> imageses) {
        this.imageses = imageses;
    }




}


